language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd 1housekeeper-front
  - npm install
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: $heroku_api_key
  app:
    master: onehousekeeper
